<Project>

  <!-- This file contains the data shared by all projects that generate a NuGet package. -->

  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <TargetFramework>net10.0</TargetFramework>
    <Version>100.1.0-alpha-2</Version>
    <Authors>Wh1teDuke</Authors>
    <PackageTags>sfml sfml.net</PackageTags>
    <Copyright>Copyright © Laurent Gomila</Copyright>

    <PackageLicenseExpression>Zlib</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/Wh1teDuke/SFML.Net.Gaiden</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Wh1teDuke/SFML.Net.Gaiden</RepositoryUrl>
    <PackageIcon>sfml-icon.png</PackageIcon>
    <PackageReadmeFile>readme.md</PackageReadmeFile>

    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.300" PrivateAssets="all" />

    <None Include="../../sfml-icon.png" Pack="true" PackagePath=""/>
    <None Include="../../readme.md" Pack="true" PackagePath="."/>
  </ItemGroup>

</Project>
