<Project>

  <!-- This file contains the data shared by all SFML Modules. -->

  <Import Project="SFML.NuGet.props" />

  <PropertyGroup>
    <IsAotCompatible>true</IsAotCompatible>
    <IsTrimmable>true</IsTrimmable>
    <VerifyReferenceTrimCompatibility>true</VerifyReferenceTrimCompatibility>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>Nullable</WarningsAsErrors>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RootNamespace>Gaiden.SFML.$(SFMLModule)</RootNamespace>

    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <Description>$(SFMLModule) module of the SFML.Net library</Description>
    <Title>SFML.Net $(SFMLModule)</Title>

    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CSFML.Gaiden" Version="[3.0.0, 3.1)" />
  </ItemGroup>

</Project>
